<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://tempuri.org/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ClnReceivableMgtServices" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SymmetricBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:ProtectionToken>
              <wsp:Policy>
                <sp:SecureConversationToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                  <wsp:Policy>
                    <sp:RequireDerivedKeys />
                    <sp:BootstrapPolicy>
                      <wsp:Policy>
                        <sp:SignedParts>
                          <sp:Body />
                          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
                        </sp:SignedParts>
                        <sp:EncryptedParts>
                          <sp:Body />
                        </sp:EncryptedParts>
                        <sp:SymmetricBinding>
                          <wsp:Policy>
                            <sp:ProtectionToken>
                              <wsp:Policy>
                                <sp:SpnegoContextToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                                  <wsp:Policy>
                                    <sp:RequireDerivedKeys />
                                  </wsp:Policy>
                                </sp:SpnegoContextToken>
                              </wsp:Policy>
                            </sp:ProtectionToken>
                            <sp:AlgorithmSuite>
                              <wsp:Policy>
                                <sp:Basic256 />
                              </wsp:Policy>
                            </sp:AlgorithmSuite>
                            <sp:Layout>
                              <wsp:Policy>
                                <sp:Strict />
                              </wsp:Policy>
                            </sp:Layout>
                            <sp:IncludeTimestamp />
                            <sp:EncryptSignature />
                            <sp:OnlySignEntireHeadersAndBody />
                          </wsp:Policy>
                        </sp:SymmetricBinding>
                        <sp:Wss11>
                          <wsp:Policy />
                        </sp:Wss11>
                        <sp:Trust10>
                          <wsp:Policy>
                            <sp:MustSupportIssuedTokens />
                            <sp:RequireClientEntropy />
                            <sp:RequireServerEntropy />
                          </wsp:Policy>
                        </sp:Trust10>
                      </wsp:Policy>
                    </sp:BootstrapPolicy>
                  </wsp:Policy>
                </sp:SecureConversationToken>
              </wsp:Policy>
            </sp:ProtectionToken>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic256 />
              </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
              <wsp:Policy>
                <sp:Strict />
              </wsp:Policy>
            </sp:Layout>
            <sp:IncludeTimestamp />
            <sp:EncryptSignature />
            <sp:OnlySignEntireHeadersAndBody />
          </wsp:Policy>
        </sp:SymmetricBinding>
        <sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy />
        </sp:Wss11>
        <sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:MustSupportIssuedTokens />
            <sp:RequireClientEntropy />
            <sp:RequireServerEntropy />
          </wsp:Policy>
        </sp:Trust10>
        <wsaw:UsingAddressing />
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDelinquentParameters_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDelinquentParameters_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDelinquentParameters_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubModifyDelinquentParameters_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubModifyDelinquentParameters_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubModifyDelinquentParameters_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubDeactivateDelinquencyType_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubDeactivateDelinquencyType_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubDeactivateDelinquencyType_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDelinquencySpooling_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDelinquencySpooling_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDelinquencySpooling_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDemandProcessing_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDemandProcessing_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDemandProcessing_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubModifyDemandProcessing_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubModifyDemandProcessing_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubModifyDemandProcessing_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateManualBucketClassifcation_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateManualBucketClassifcation_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateManualBucketClassifcation_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubModifyManualBucketClassifcationcategory_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubModifyManualBucketClassifcationcategory_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubModifyManualBucketClassifcationcategory_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateBucketParameterDetails_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateBucketParameterDetails_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateBucketParameterDetails_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateLoanToValue_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateLoanToValue_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateLoanToValue_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateMarketValueEntry_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateMarketValueEntry_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateMarketValueEntry_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateMarketValueEntryGL_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateMarketValueEntryGL_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateMarketValueEntryGL_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunMarketEntryForModification_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunMarketEntryForModification_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunMarketEntryForModification_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateandModifyDCRDetails_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateandModifyDCRDetails_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IClnReceivableMgtServices_FunPubCreateandModifyDCRDetails_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsdl:types>
    <xsd:schema targetNamespace="http://tempuri.org/Imports">
      <xsd:import schemaLocation="http://localhost:3220/Collection/ClnReceivableMgtServices.svc?xsd=xsd0" namespace="http://tempuri.org/" />
      <xsd:import schemaLocation="http://localhost:3220/Collection/ClnReceivableMgtServices.svc?xsd=xsd3" namespace="http://schemas.datacontract.org/2004/07/S3GServiceLayer" />
      <xsd:import schemaLocation="http://localhost:3220/Collection/ClnReceivableMgtServices.svc?xsd=xsd1" namespace="http://schemas.microsoft.com/2003/10/Serialization/" />
      <xsd:import schemaLocation="http://localhost:3220/Collection/ClnReceivableMgtServices.svc?xsd=xsd2" namespace="http://schemas.datacontract.org/2004/07/S3GBusEntity" />
      <xsd:import schemaLocation="http://localhost:3220/Collection/ClnReceivableMgtServices.svc?xsd=xsd4" namespace="http://schemas.datacontract.org/2004/07/System.Data" />
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateDelinquentParameters_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateDelinquentParameters" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateDelinquentParameters_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateDelinquentParametersResponse" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateDelinquentParameters_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q1="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q1:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubModifyDelinquentParameters_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubModifyDelinquentParameters" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubModifyDelinquentParameters_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubModifyDelinquentParametersResponse" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubModifyDelinquentParameters_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q2="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q2:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubDeactivateDelinquencyType_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubDeactivateDelinquencyType" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubDeactivateDelinquencyType_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubDeactivateDelinquencyTypeResponse" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubDeactivateDelinquencyType_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q3="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q3:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateDelinquencySpooling_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateDelinquencySpooling" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateDelinquencySpooling_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateDelinquencySpoolingResponse" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateDelinquencySpooling_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q4="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q4:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateDemandProcessing_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateDemandProcessing" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateDemandProcessing_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateDemandProcessingResponse" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateDemandProcessing_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q5="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q5:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubModifyDemandProcessing_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubModifyDemandProcessing" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubModifyDemandProcessing_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubModifyDemandProcessingResponse" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubModifyDemandProcessing_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q6="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q6:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateManualBucketClassifcation_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateManualBucketClassifcation" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateManualBucketClassifcation_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateManualBucketClassifcationResponse" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateManualBucketClassifcation_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q7="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q7:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubModifyManualBucketClassifcationcategory_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubModifyManualBucketClassifcationcategory" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubModifyManualBucketClassifcationcategory_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubModifyManualBucketClassifcationcategoryResponse" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubModifyManualBucketClassifcationcategory_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q8="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q8:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateBucketParameterDetails_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateBucketParameterDetails" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateBucketParameterDetails_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateBucketParameterDetailsResponse" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateBucketParameterDetails_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q9="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q9:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateLoanToValue_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateLoanToValue" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateLoanToValue_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateLoanToValueResponse" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateLoanToValue_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q10="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q10:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateMarketValueEntry_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateMarketValueEntry" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateMarketValueEntry_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateMarketValueEntryResponse" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateMarketValueEntry_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q11="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q11:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateMarketValueEntryGL_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateMarketValueEntryGL" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateMarketValueEntryGL_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateMarketValueEntryGLResponse" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateMarketValueEntryGL_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q12="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q12:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunMarketEntryForModification_InputMessage">
    <wsdl:part name="parameters" element="tns:FunMarketEntryForModification" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunMarketEntryForModification_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunMarketEntryForModificationResponse" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunMarketEntryForModification_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q13="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q13:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateandModifyDCRDetails_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateandModifyDCRDetails" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateandModifyDCRDetails_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateandModifyDCRDetailsResponse" />
  </wsdl:message>
  <wsdl:message name="IClnReceivableMgtServices_FunPubCreateandModifyDCRDetails_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q14="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q14:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:portType name="IClnReceivableMgtServices">
    <wsdl:operation name="FunPubCreateDelinquentParameters">
      <wsdl:input wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateDelinquentParameters" message="tns:IClnReceivableMgtServices_FunPubCreateDelinquentParameters_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateDelinquentParametersResponse" message="tns:IClnReceivableMgtServices_FunPubCreateDelinquentParameters_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateDelinquentParametersClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IClnReceivableMgtServices_FunPubCreateDelinquentParameters_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubModifyDelinquentParameters">
      <wsdl:input wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubModifyDelinquentParameters" message="tns:IClnReceivableMgtServices_FunPubModifyDelinquentParameters_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubModifyDelinquentParametersResponse" message="tns:IClnReceivableMgtServices_FunPubModifyDelinquentParameters_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubModifyDelinquentParametersClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IClnReceivableMgtServices_FunPubModifyDelinquentParameters_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubDeactivateDelinquencyType">
      <wsdl:input wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubDeactivateDelinquencyType" message="tns:IClnReceivableMgtServices_FunPubDeactivateDelinquencyType_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubDeactivateDelinquencyTypeResponse" message="tns:IClnReceivableMgtServices_FunPubDeactivateDelinquencyType_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubDeactivateDelinquencyTypeClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IClnReceivableMgtServices_FunPubDeactivateDelinquencyType_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateDelinquencySpooling">
      <wsdl:input wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateDelinquencySpooling" message="tns:IClnReceivableMgtServices_FunPubCreateDelinquencySpooling_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateDelinquencySpoolingResponse" message="tns:IClnReceivableMgtServices_FunPubCreateDelinquencySpooling_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateDelinquencySpoolingClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IClnReceivableMgtServices_FunPubCreateDelinquencySpooling_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateDemandProcessing">
      <wsdl:input wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateDemandProcessing" message="tns:IClnReceivableMgtServices_FunPubCreateDemandProcessing_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateDemandProcessingResponse" message="tns:IClnReceivableMgtServices_FunPubCreateDemandProcessing_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateDemandProcessingClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IClnReceivableMgtServices_FunPubCreateDemandProcessing_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubModifyDemandProcessing">
      <wsdl:input wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubModifyDemandProcessing" message="tns:IClnReceivableMgtServices_FunPubModifyDemandProcessing_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubModifyDemandProcessingResponse" message="tns:IClnReceivableMgtServices_FunPubModifyDemandProcessing_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubModifyDemandProcessingClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IClnReceivableMgtServices_FunPubModifyDemandProcessing_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateManualBucketClassifcation">
      <wsdl:input wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateManualBucketClassifcation" message="tns:IClnReceivableMgtServices_FunPubCreateManualBucketClassifcation_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateManualBucketClassifcationResponse" message="tns:IClnReceivableMgtServices_FunPubCreateManualBucketClassifcation_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateManualBucketClassifcationClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IClnReceivableMgtServices_FunPubCreateManualBucketClassifcation_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubModifyManualBucketClassifcationcategory">
      <wsdl:input wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubModifyManualBucketClassifcationcategory" message="tns:IClnReceivableMgtServices_FunPubModifyManualBucketClassifcationcategory_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubModifyManualBucketClassifcationcategoryResponse" message="tns:IClnReceivableMgtServices_FunPubModifyManualBucketClassifcationcategory_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubModifyManualBucketClassifcationcategoryClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IClnReceivableMgtServices_FunPubModifyManualBucketClassifcationcategory_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateBucketParameterDetails">
      <wsdl:input wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateBucketParameterDetails" message="tns:IClnReceivableMgtServices_FunPubCreateBucketParameterDetails_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateBucketParameterDetailsResponse" message="tns:IClnReceivableMgtServices_FunPubCreateBucketParameterDetails_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateBucketParameterDetailsClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IClnReceivableMgtServices_FunPubCreateBucketParameterDetails_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateLoanToValue">
      <wsdl:input wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateLoanToValue" message="tns:IClnReceivableMgtServices_FunPubCreateLoanToValue_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateLoanToValueResponse" message="tns:IClnReceivableMgtServices_FunPubCreateLoanToValue_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateLoanToValueClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IClnReceivableMgtServices_FunPubCreateLoanToValue_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateMarketValueEntry">
      <wsdl:input wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateMarketValueEntry" message="tns:IClnReceivableMgtServices_FunPubCreateMarketValueEntry_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateMarketValueEntryResponse" message="tns:IClnReceivableMgtServices_FunPubCreateMarketValueEntry_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateMarketValueEntryClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IClnReceivableMgtServices_FunPubCreateMarketValueEntry_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateMarketValueEntryGL">
      <wsdl:input wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateMarketValueEntryGL" message="tns:IClnReceivableMgtServices_FunPubCreateMarketValueEntryGL_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateMarketValueEntryGLResponse" message="tns:IClnReceivableMgtServices_FunPubCreateMarketValueEntryGL_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateMarketValueEntryGLClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IClnReceivableMgtServices_FunPubCreateMarketValueEntryGL_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunMarketEntryForModification">
      <wsdl:input wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunMarketEntryForModification" message="tns:IClnReceivableMgtServices_FunMarketEntryForModification_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunMarketEntryForModificationResponse" message="tns:IClnReceivableMgtServices_FunMarketEntryForModification_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunMarketEntryForModificationClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IClnReceivableMgtServices_FunMarketEntryForModification_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateandModifyDCRDetails">
      <wsdl:input wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateandModifyDCRDetails" message="tns:IClnReceivableMgtServices_FunPubCreateandModifyDCRDetails_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateandModifyDCRDetailsResponse" message="tns:IClnReceivableMgtServices_FunPubCreateandModifyDCRDetails_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateandModifyDCRDetailsClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IClnReceivableMgtServices_FunPubCreateandModifyDCRDetails_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="WSHttpBinding_IClnReceivableMgtServices" type="tns:IClnReceivableMgtServices">
    <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_policy" />
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="FunPubCreateDelinquentParameters">
      <soap12:operation soapAction="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateDelinquentParameters" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDelinquentParameters_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDelinquentParameters_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDelinquentParameters_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubModifyDelinquentParameters">
      <soap12:operation soapAction="http://tempuri.org/IClnReceivableMgtServices/FunPubModifyDelinquentParameters" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubModifyDelinquentParameters_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubModifyDelinquentParameters_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubModifyDelinquentParameters_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubDeactivateDelinquencyType">
      <soap12:operation soapAction="http://tempuri.org/IClnReceivableMgtServices/FunPubDeactivateDelinquencyType" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubDeactivateDelinquencyType_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubDeactivateDelinquencyType_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubDeactivateDelinquencyType_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateDelinquencySpooling">
      <soap12:operation soapAction="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateDelinquencySpooling" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDelinquencySpooling_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDelinquencySpooling_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDelinquencySpooling_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateDemandProcessing">
      <soap12:operation soapAction="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateDemandProcessing" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDemandProcessing_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDemandProcessing_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateDemandProcessing_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubModifyDemandProcessing">
      <soap12:operation soapAction="http://tempuri.org/IClnReceivableMgtServices/FunPubModifyDemandProcessing" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubModifyDemandProcessing_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubModifyDemandProcessing_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubModifyDemandProcessing_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateManualBucketClassifcation">
      <soap12:operation soapAction="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateManualBucketClassifcation" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateManualBucketClassifcation_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateManualBucketClassifcation_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateManualBucketClassifcation_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubModifyManualBucketClassifcationcategory">
      <soap12:operation soapAction="http://tempuri.org/IClnReceivableMgtServices/FunPubModifyManualBucketClassifcationcategory" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubModifyManualBucketClassifcationcategory_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubModifyManualBucketClassifcationcategory_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubModifyManualBucketClassifcationcategory_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateBucketParameterDetails">
      <soap12:operation soapAction="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateBucketParameterDetails" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateBucketParameterDetails_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateBucketParameterDetails_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateBucketParameterDetails_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateLoanToValue">
      <soap12:operation soapAction="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateLoanToValue" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateLoanToValue_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateLoanToValue_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateLoanToValue_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateMarketValueEntry">
      <soap12:operation soapAction="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateMarketValueEntry" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateMarketValueEntry_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateMarketValueEntry_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateMarketValueEntry_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateMarketValueEntryGL">
      <soap12:operation soapAction="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateMarketValueEntryGL" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateMarketValueEntryGL_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateMarketValueEntryGL_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateMarketValueEntryGL_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunMarketEntryForModification">
      <soap12:operation soapAction="http://tempuri.org/IClnReceivableMgtServices/FunMarketEntryForModification" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunMarketEntryForModification_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunMarketEntryForModification_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunMarketEntryForModification_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateandModifyDCRDetails">
      <soap12:operation soapAction="http://tempuri.org/IClnReceivableMgtServices/FunPubCreateandModifyDCRDetails" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateandModifyDCRDetails_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateandModifyDCRDetails_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IClnReceivableMgtServices_FunPubCreateandModifyDCRDetails_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ClnReceivableMgtServices">
    <wsdl:port name="WSHttpBinding_IClnReceivableMgtServices" binding="tns:WSHttpBinding_IClnReceivableMgtServices">
      <soap12:address location="http://localhost:3220/Collection/ClnReceivableMgtServices.svc" />
      <wsa10:EndpointReference>
        <wsa10:Address>http://localhost:3220/Collection/ClnReceivableMgtServices.svc</wsa10:Address>
        <Identity xmlns="http://schemas.xmlsoap.org/ws/2006/02/addressingidentity">
          <Dns>localhost</Dns>
        </Identity>
      </wsa10:EndpointReference>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>