//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMsgs_FA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMsgs_FA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ValidationMsgs_FA", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot revoke the record which is in closed month..
        /// </summary>
        internal static string APPR_Month_Clsr {
            get {
                return ResourceManager.GetString("APPR_Month_Clsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found for the selected category.
        /// </summary>
        internal static string CBC_1 {
            get {
                return ResourceManager.GetString("CBC_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the \&quot;Change To\&quot; option.
        /// </summary>
        internal static string CBC_10 {
            get {
                return ResourceManager.GetString("CBC_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not made any changes.
        /// </summary>
        internal static string CBC_11 {
            get {
                return ResourceManager.GetString("CBC_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select atleast one row to Reassign.
        /// </summary>
        internal static string CBC_2 {
            get {
                return ResourceManager.GetString("CBC_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt Collector Reassigned Successfully.
        /// </summary>
        internal static string CBC_3 {
            get {
                return ResourceManager.GetString("CBC_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Reassigning Debt Collector.
        /// </summary>
        internal static string CBC_4 {
            get {
                return ResourceManager.GetString("CBC_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Change To Debt Collector.
        /// </summary>
        internal static string CBC_5 {
            get {
                return ResourceManager.GetString("CBC_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Category is already assigned for the Contract.
        /// </summary>
        internal static string CBC_6 {
            get {
                return ResourceManager.GetString("CBC_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Reassigned Successfully.
        /// </summary>
        internal static string CBC_7 {
            get {
                return ResourceManager.GetString("CBC_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Reassigning Category.
        /// </summary>
        internal static string CBC_8 {
            get {
                return ResourceManager.GetString("CBC_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Change To Category.
        /// </summary>
        internal static string CBC_9 {
            get {
                return ResourceManager.GetString("CBC_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target directory was not found.
        /// </summary>
        internal static string CDI_1 {
            get {
                return ResourceManager.GetString("CDI_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found to generate Excel.
        /// </summary>
        internal static string CDI_2 {
            get {
                return ResourceManager.GetString("CDI_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot export file. MS-Excel is not available.
        /// </summary>
        internal static string CDI_3 {
            get {
                return ResourceManager.GetString("CDI_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast one record required to save.
        /// </summary>
        internal static string CDI_4 {
            get {
                return ResourceManager.GetString("CDI_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC Incentive Processing details saved successfully.
        /// </summary>
        internal static string CDI_5 {
            get {
                return ResourceManager.GetString("CDI_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC Incentive Processing record already exist.
        /// </summary>
        internal static string CDI_6 {
            get {
                return ResourceManager.GetString("CDI_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CDI_7 {
            get {
                return ResourceManager.GetString("CDI_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Atleast one Row in Delinquency Parameter grid.
        /// </summary>
        internal static string CDL_1 {
            get {
                return ResourceManager.GetString("CDL_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Month should not be lesser than From Month.
        /// </summary>
        internal static string CDL_10 {
            get {
                return ResourceManager.GetString("CDL_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From values need to be distinct.
        /// </summary>
        internal static string CDL_11 {
            get {
                return ResourceManager.GetString("CDL_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From and To Month combination exceeds previous.
        /// </summary>
        internal static string CDL_12 {
            get {
                return ResourceManager.GetString("CDL_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From and To Month should not be overlaped.
        /// </summary>
        internal static string CDL_13 {
            get {
                return ResourceManager.GetString("CDL_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter cut off month.
        /// </summary>
        internal static string CDL_14 {
            get {
                return ResourceManager.GetString("CDL_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Secured Principal % and UnSecured Principal % cannot be zero.
        /// </summary>
        internal static string CDL_15 {
            get {
                return ResourceManager.GetString("CDL_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsecured Principal % should be greater than previous Unsecured Principal %.
        /// </summary>
        internal static string CDL_16 {
            get {
                return ResourceManager.GetString("CDL_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured Principal % should be greater than previous Secured Principal %.
        /// </summary>
        internal static string CDL_17 {
            get {
                return ResourceManager.GetString("CDL_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delinquency parameter Updated sucessfully.
        /// </summary>
        internal static string CDL_2 {
            get {
                return ResourceManager.GetString("CDL_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Sequence Number not yet defined for Delinquency Parameter.
        /// </summary>
        internal static string CDL_3 {
            get {
                return ResourceManager.GetString("CDL_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delinquency Parameter already defined for this combination.
        /// </summary>
        internal static string CDL_4 {
            get {
                return ResourceManager.GetString("CDL_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delinquency Parameter already  defined at Company Level.
        /// </summary>
        internal static string CDL_5 {
            get {
                return ResourceManager.GetString("CDL_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter \&quot;From Month\&quot;.
        /// </summary>
        internal static string CDL_6 {
            get {
                return ResourceManager.GetString("CDL_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter \&quot;To Month\&quot;.
        /// </summary>
        internal static string CDL_7 {
            get {
                return ResourceManager.GetString("CDL_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Unsecure Principle Percentage.
        /// </summary>
        internal static string CDL_8 {
            get {
                return ResourceManager.GetString("CDL_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Secure Principle Percentage.
        /// </summary>
        internal static string CDL_9 {
            get {
                return ResourceManager.GetString("CDL_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;To value\&quot; should be greater than \&quot;From value\&quot;.
        /// </summary>
        internal static string CLNBUK_13 {
            get {
                return ResourceManager.GetString("CLNBUK_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9 Rows only allowed.
        /// </summary>
        internal static string CLNBUK_14 {
            get {
                return ResourceManager.GetString("CLNBUK_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to data problem, Unable to load the bucket parameter details.
        /// </summary>
        internal static string CLNBUK_15 {
            get {
                return ResourceManager.GetString("CLNBUK_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load Category Type.
        /// </summary>
        internal static string CLNBUK_16 {
            get {
                return ResourceManager.GetString("CLNBUK_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add new row in value gridview.
        /// </summary>
        internal static string CLNBUK_17 {
            get {
                return ResourceManager.GetString("CLNBUK_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete row in value gridview.
        /// </summary>
        internal static string CLNBUK_18 {
            get {
                return ResourceManager.GetString("CLNBUK_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add new row in days gridview.
        /// </summary>
        internal static string CLNBUK_19 {
            get {
                return ResourceManager.GetString("CLNBUK_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Days or Values or Category details.
        /// </summary>
        internal static string CLNBUK_2 {
            get {
                return ResourceManager.GetString("CLNBUK_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete the row in  days gridview.
        /// </summary>
        internal static string CLNBUK_20 {
            get {
                return ResourceManager.GetString("CLNBUK_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert/modify Bucket Parameter .
        /// </summary>
        internal static string CLNBUK_21 {
            get {
                return ResourceManager.GetString("CLNBUK_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to redirect the page.
        /// </summary>
        internal static string CLNBUK_22 {
            get {
                return ResourceManager.GetString("CLNBUK_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Clear_FA the controls.
        /// </summary>
        internal static string CLNBUK_23 {
            get {
                return ResourceManager.GetString("CLNBUK_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days should not be overlap.
        /// </summary>
        internal static string CLNBUK_24 {
            get {
                return ResourceManager.GetString("CLNBUK_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket Parameter already exists.
        /// </summary>
        internal static string CLNBUK_25 {
            get {
                return ResourceManager.GetString("CLNBUK_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Value details.
        /// </summary>
        internal static string CLNBUK_3 {
            get {
                return ResourceManager.GetString("CLNBUK_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This combination of Category Type is already defined.
        /// </summary>
        internal static string CLNBUK_4 {
            get {
                return ResourceManager.GetString("CLNBUK_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;From value\&quot; must be entered.
        /// </summary>
        internal static string CLNBUK_5 {
            get {
                return ResourceManager.GetString("CLNBUK_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;To value\&quot; must be entered.
        /// </summary>
        internal static string CLNBUK_6 {
            get {
                return ResourceManager.GetString("CLNBUK_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Description.
        /// </summary>
        internal static string CLNBUK_7 {
            get {
                return ResourceManager.GetString("CLNBUK_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;To days\&quot; should be greater than \&quot;From days\&quot;.
        /// </summary>
        internal static string CLNBUK_8 {
            get {
                return ResourceManager.GetString("CLNBUK_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values should not be overlap.
        /// </summary>
        internal static string CLNBUK_9 {
            get {
                return ResourceManager.GetString("CLNBUK_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load Prime Account number.
        /// </summary>
        internal static string CLNPDC_1 {
            get {
                return ResourceManager.GetString("CLNPDC_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction date should not  greater than posting date.
        /// </summary>
        internal static string CLNPDC_11 {
            get {
                return ResourceManager.GetString("CLNPDC_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Instrument Number.
        /// </summary>
        internal static string CLNPDC_12 {
            get {
                return ResourceManager.GetString("CLNPDC_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Prime Account Number.
        /// </summary>
        internal static string CLNPDC_13 {
            get {
                return ResourceManager.GetString("CLNPDC_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Sub Account Number.
        /// </summary>
        internal static string CLNPDC_14 {
            get {
                return ResourceManager.GetString("CLNPDC_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Transaction Date.
        /// </summary>
        internal static string CLNPDC_15 {
            get {
                return ResourceManager.GetString("CLNPDC_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Posting Date.
        /// </summary>
        internal static string CLNPDC_16 {
            get {
                return ResourceManager.GetString("CLNPDC_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load Sub Account Number.
        /// </summary>
        internal static string CLNPDC_2 {
            get {
                return ResourceManager.GetString("CLNPDC_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Load PDC details.
        /// </summary>
        internal static string CLNPDC_3 {
            get {
                return ResourceManager.GetString("CLNPDC_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert/modify the PDC details.
        /// </summary>
        internal static string CLNPDC_4 {
            get {
                return ResourceManager.GetString("CLNPDC_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to bind the records in PDC details.
        /// </summary>
        internal static string CLNPDC_5 {
            get {
                return ResourceManager.GetString("CLNPDC_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Instrument Sequence.
        /// </summary>
        internal static string CLNPDC_6 {
            get {
                return ResourceManager.GetString("CLNPDC_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Instrument Type.
        /// </summary>
        internal static string CLNPDC_8 {
            get {
                return ResourceManager.GetString("CLNPDC_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the instrument starting number.
        /// </summary>
        internal static string CLNPDC_9 {
            get {
                return ResourceManager.GetString("CLNPDC_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appropriation logic already exists at Company Level.
        /// </summary>
        internal static string CLN_ApprLogic_CompanyLevel {
            get {
                return ResourceManager.GetString("CLN_ApprLogic_CompanyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update changes in Appropriation Logic Details..
        /// </summary>
        internal static string CLN_ApprLogic_GridUpdate {
            get {
                return ResourceManager.GetString("CLN_ApprLogic_GridUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appropriation logic already exists.
        /// </summary>
        internal static string CLN_ApprLogic_LOBLevel {
            get {
                return ResourceManager.GetString("CLN_ApprLogic_LOBLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Percentage..
        /// </summary>
        internal static string CLN_ApprLogic_Percent {
            get {
                return ResourceManager.GetString("CLN_ApprLogic_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Drawee Bank Name.
        /// </summary>
        internal static string CLN_CCR_1 {
            get {
                return ResourceManager.GetString("CLN_CCR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to data problem, unable to load the .
        /// </summary>
        internal static string CLN_CCR_10 {
            get {
                return ResourceManager.GetString("CLN_CCR_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This combination of bank details is already exists.
        /// </summary>
        internal static string CLN_CCR_2 {
            get {
                return ResourceManager.GetString("CLN_CCR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Drawee Bank Name.
        /// </summary>
        internal static string CLN_CCR_3 {
            get {
                return ResourceManager.GetString("CLN_CCR_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Drawee Bank is already mapped with another Deposit Bank.
        /// </summary>
        internal static string CLN_CCR_4 {
            get {
                return ResourceManager.GetString("CLN_CCR_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Drawee Bank is already exists.
        /// </summary>
        internal static string CLN_CCR_5 {
            get {
                return ResourceManager.GetString("CLN_CCR_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete the records from Drawee Bank Name.
        /// </summary>
        internal static string CLN_CCR_6 {
            get {
                return ResourceManager.GetString("CLN_CCR_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add new row in Drawee Bank Name.
        /// </summary>
        internal static string CLN_CCR_7 {
            get {
                return ResourceManager.GetString("CLN_CCR_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Load the Drawee Bank Name.
        /// </summary>
        internal static string CLN_CCR_8 {
            get {
                return ResourceManager.GetString("CLN_CCR_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert/modify the Challan Rules.
        /// </summary>
        internal static string CLN_CCR_9 {
            get {
                return ResourceManager.GetString("CLN_CCR_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt not available for Challan Generation.
        /// </summary>
        internal static string CLN_CHN_1 {
            get {
                return ResourceManager.GetString("CLN_CHN_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include any one of the receipt  for Challan Generation.
        /// </summary>
        internal static string CLN_CHN_2 {
            get {
                return ResourceManager.GetString("CLN_CHN_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Recognition has been done already for this combination.
        /// </summary>
        internal static string CLN_CIR_1 {
            get {
                return ResourceManager.GetString("CLN_CIR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Recognition Method is not defined in global parameter setup.
        /// </summary>
        internal static string CLN_CIR_10 {
            get {
                return ResourceManager.GetString("CLN_CIR_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Recognition Type is not defined in global parameter setup.
        /// </summary>
        internal static string CLN_CIR_11 {
            get {
                return ResourceManager.GetString("CLN_CIR_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous month should be closed for the selected  Location(s).
        /// </summary>
        internal static string CLN_CIR_12 {
            get {
                return ResourceManager.GetString("CLN_CIR_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accounts found to calculate Income Recognition .
        /// </summary>
        internal static string CLN_CIR_2 {
            get {
                return ResourceManager.GetString("CLN_CIR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutoff Date month is closed for the selected Location(s).
        /// </summary>
        internal static string CLN_CIR_3 {
            get {
                return ResourceManager.GetString("CLN_CIR_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revocation can be done sequentially only.
        /// </summary>
        internal static string CLN_CIR_4 {
            get {
                return ResourceManager.GetString("CLN_CIR_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Calculation date should be greater than last Income calculation date  for the selected Location(s).
        /// </summary>
        internal static string CLN_CIR_5 {
            get {
                return ResourceManager.GetString("CLN_CIR_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing should be done for the selected Location(s) before income calculation.
        /// </summary>
        internal static string CLN_CIR_6 {
            get {
                return ResourceManager.GetString("CLN_CIR_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Sequence Number not defined for the selected Location(s).
        /// </summary>
        internal static string CLN_CIR_7 {
            get {
                return ResourceManager.GetString("CLN_CIR_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Sequence Number limit is exceeded  for the selected Location(s).
        /// </summary>
        internal static string CLN_CIR_8 {
            get {
                return ResourceManager.GetString("CLN_CIR_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No accounts found in the specified income method. Check global parameter setup for Income recognition.
        /// </summary>
        internal static string CLN_CIR_9 {
            get {
                return ResourceManager.GetString("CLN_CIR_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revocation done successfully.
        /// </summary>
        internal static string CLN_CIR_Revoke {
            get {
                return ResourceManager.GetString("CLN_CIR_Revoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since the first record enter for month the next record period should be.
        /// </summary>
        internal static string CLN_DCM_ErrMsg_PeriodFormat_Month {
            get {
                return ResourceManager.GetString("CLN_DCM_ErrMsg_PeriodFormat_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since the first record enter for year the next record period should be.
        /// </summary>
        internal static string CLN_DCM_ErrMsg_PeriodFormat_Year {
            get {
                return ResourceManager.GetString("CLN_DCM_ErrMsg_PeriodFormat_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the period in order wise from the starting year.
        /// </summary>
        internal static string CLN_DCM_ErrMsg_PeriodOrder {
            get {
                return ResourceManager.GetString("CLN_DCM_ErrMsg_PeriodOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The period starting month is  .
        /// </summary>
        internal static string CLN_DCM_ErrMsg_PeriodStartMonth {
            get {
                return ResourceManager.GetString("CLN_DCM_ErrMsg_PeriodStartMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Memo Details.
        /// </summary>
        internal static string CLN_MM_1 {
            get {
                return ResourceManager.GetString("CLN_MM_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Memo Description.
        /// </summary>
        internal static string CLN_MM_2 {
            get {
                return ResourceManager.GetString("CLN_MM_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the GL Account.
        /// </summary>
        internal static string CLN_MM_3 {
            get {
                return ResourceManager.GetString("CLN_MM_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the SL Account.
        /// </summary>
        internal static string CLN_MM_4 {
            get {
                return ResourceManager.GetString("CLN_MM_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select another Memo Details.
        /// </summary>
        internal static string CLN_MM_5 {
            get {
                return ResourceManager.GetString("CLN_MM_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo Details already exists.
        /// </summary>
        internal static string CLN_MM_Exist {
            get {
                return ResourceManager.GetString("CLN_MM_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo Details added successfully.
        /// </summary>
        internal static string CLN_MM_Save {
            get {
                return ResourceManager.GetString("CLN_MM_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo Details updated successfully.
        /// </summary>
        internal static string CLN_MM_Update {
            get {
                return ResourceManager.GetString("CLN_MM_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target directory was not found.
        /// </summary>
        internal static string CLV_1 {
            get {
                return ResourceManager.GetString("CLV_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan To Value Spooling saved successfully.
        /// </summary>
        internal static string CLV_2 {
            get {
                return ResourceManager.GetString("CLV_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update Loan To Value Spooling - which was already saved for the displaying Report Date/Line of Business/Location.
        /// </summary>
        internal static string CLV_3 {
            get {
                return ResourceManager.GetString("CLV_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can save, only after you create the grid - Click on Go Button.
        /// </summary>
        internal static string CLV_4 {
            get {
                return ResourceManager.GetString("CLV_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create an Excel, only after you create the grid - Click on Go Button.
        /// </summary>
        internal static string CLV_5 {
            get {
                return ResourceManager.GetString("CLV_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no record to spool for this combination.
        /// </summary>
        internal static string CLV_6 {
            get {
                return ResourceManager.GetString("CLV_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create a Flat File, only after you create the grid - Click on Go Button.
        /// </summary>
        internal static string CLV_7 {
            get {
                return ResourceManager.GetString("CLV_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice cannot be updated. Application Approved.
        /// </summary>
        internal static string LOANAD_INV_10 {
            get {
                return ResourceManager.GetString("LOANAD_INV_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice has already been generated for all the assets mapped to this.
        /// </summary>
        internal static string LOANAD_INV_11 {
            get {
                return ResourceManager.GetString("LOANAD_INV_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice date should be greater than or equal to Application Creation date.
        /// </summary>
        internal static string LOANAD_INV_12 {
            get {
                return ResourceManager.GetString("LOANAD_INV_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice date should be greater than or equal to Enquiry Response date.
        /// </summary>
        internal static string LOANAD_INV_13 {
            get {
                return ResourceManager.GetString("LOANAD_INV_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice date should be greater than or equal to Pricing date.
        /// </summary>
        internal static string LOANAD_INV_14 {
            get {
                return ResourceManager.GetString("LOANAD_INV_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice date should be greater than or equal to Application creation date.
        /// </summary>
        internal static string LOANAD_INV_15 {
            get {
                return ResourceManager.GetString("LOANAD_INV_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice cannot be updated. Asset Acquisition is done for this LPO.
        /// </summary>
        internal static string LOANAD_INV_16 {
            get {
                return ResourceManager.GetString("LOANAD_INV_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice cannot be updated. Account has been activated.
        /// </summary>
        internal static string LOANAD_INV_3 {
            get {
                return ResourceManager.GetString("LOANAD_INV_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Number already exists.
        /// </summary>
        internal static string LOANAD_INV_4 {
            get {
                return ResourceManager.GetString("LOANAD_INV_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of units greater than actual units .
        /// </summary>
        internal static string LOANAD_INV_6 {
            get {
                return ResourceManager.GetString("LOANAD_INV_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of units cannot be reduced. Asset(s) already identified.
        /// </summary>
        internal static string LOANAD_INV_7 {
            get {
                return ResourceManager.GetString("LOANAD_INV_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice cannot be updated. Credit Parameter Approved.
        /// </summary>
        internal static string LOANAD_INV_8 {
            get {
                return ResourceManager.GetString("LOANAD_INV_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice cannot be updated. Pricing Approved.
        /// </summary>
        internal static string LOANAD_INV_9 {
            get {
                return ResourceManager.GetString("LOANAD_INV_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Load the Lease Asset Sale.
        /// </summary>
        internal static string LoanAd_LaAsstsale_1 {
            get {
                return ResourceManager.GetString("LoanAd_LaAsstsale_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Code is Required.
        /// </summary>
        internal static string LoanAd_LaAsstsale_10 {
            get {
                return ResourceManager.GetString("LoanAd_LaAsstsale_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lease Asset Number is Required.
        /// </summary>
        internal static string LoanAd_LaAsstsale_11 {
            get {
                return ResourceManager.GetString("LoanAd_LaAsstsale_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sevice Tax or VAT atleast one should be entered.
        /// </summary>
        internal static string LoanAd_LaAsstsale_12 {
            get {
                return ResourceManager.GetString("LoanAd_LaAsstsale_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual value has to be greater or equal to residual Value.
        /// </summary>
        internal static string LoanAd_LaAsstsale_13 {
            get {
                return ResourceManager.GetString("LoanAd_LaAsstsale_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Asset cannot be sold to to this customer since he was a leasor of this asset.
        /// </summary>
        internal static string LoanAd_LaAsstsale_15 {
            get {
                return ResourceManager.GetString("LoanAd_LaAsstsale_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Load the Asset Details.
        /// </summary>
        internal static string LoanAd_LaAsstsale_2 {
            get {
                return ResourceManager.GetString("LoanAd_LaAsstsale_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Load Entiry Code.
        /// </summary>
        internal static string LoanAd_LaAsstsale_3 {
            get {
                return ResourceManager.GetString("LoanAd_LaAsstsale_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Disable Lease Asset Type.
        /// </summary>
        internal static string LoanAd_LaAsstsale_4 {
            get {
                return ResourceManager.GetString("LoanAd_LaAsstsale_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Clear_FA the Controls.
        /// </summary>
        internal static string LoanAd_LaAsstsale_5 {
            get {
                return ResourceManager.GetString("LoanAd_LaAsstsale_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Redirect the Page.
        /// </summary>
        internal static string LoanAd_LaAsstsale_6 {
            get {
                return ResourceManager.GetString("LoanAd_LaAsstsale_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Save the Lease Asset Sale details.
        /// </summary>
        internal static string LoanAd_LaAsstsale_7 {
            get {
                return ResourceManager.GetString("LoanAd_LaAsstsale_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Generate PDF File.
        /// </summary>
        internal static string LoanAd_LaAsstsale_8 {
            get {
                return ResourceManager.GetString("LoanAd_LaAsstsale_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MJV Date month is closed Lease Asset Sale details cannot be created or Updated.
        /// </summary>
        internal static string LoanAd_LaAsstsale_9 {
            get {
                return ResourceManager.GetString("LoanAd_LaAsstsale_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual journal details already exists.
        /// </summary>
        internal static string LOANAD_MJV_1 {
            get {
                return ResourceManager.GetString("LOANAD_MJV_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected account(s) creation date should be less than or equal to MJV Value date.
        /// </summary>
        internal static string LOANAD_MJV_10 {
            get {
                return ResourceManager.GetString("LOANAD_MJV_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected account(s) creation date should be less than or equal to MJV date.
        /// </summary>
        internal static string LOANAD_MJV_11 {
            get {
                return ResourceManager.GetString("LOANAD_MJV_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record approval status is under process. Manual Journal details cannot be updated.
        /// </summary>
        internal static string LOANAD_MJV_2 {
            get {
                return ResourceManager.GetString("LOANAD_MJV_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record is approved. Manual Journal details cannot be updated.
        /// </summary>
        internal static string LOANAD_MJV_3 {
            get {
                return ResourceManager.GetString("LOANAD_MJV_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record  approval status is rejected. Manual Journal details cannot be updated.
        /// </summary>
        internal static string LOANAD_MJV_4 {
            get {
                return ResourceManager.GetString("LOANAD_MJV_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MJV value date month closed. Manual Journal details cannot be created or updated.
        /// </summary>
        internal static string LOANAD_MJV_5 {
            get {
                return ResourceManager.GetString("LOANAD_MJV_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MJV value date cannot be less than previous records MJV value date.
        /// </summary>
        internal static string LOANAD_MJV_6 {
            get {
                return ResourceManager.GetString("LOANAD_MJV_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MJV date should be greater than or equal to account(s) creation date .
        /// </summary>
        internal static string LOANAD_MJV_7 {
            get {
                return ResourceManager.GetString("LOANAD_MJV_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MJV record canbe cancelled only in approval status is pending.
        /// </summary>
        internal static string LOANAD_MJV_8 {
            get {
                return ResourceManager.GetString("LOANAD_MJV_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MJV value date should be greater than or equal to account(s) creation date.
        /// </summary>
        internal static string LOANAD_MJV_9 {
            get {
                return ResourceManager.GetString("LOANAD_MJV_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depreciation calculation date is closed. Revocation cannot be done.
        /// </summary>
        internal static string OLDP_105 {
            get {
                return ResourceManager.GetString("OLDP_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revocation can be done only for latest depreciation record.
        /// </summary>
        internal static string OLDP_106 {
            get {
                return ResourceManager.GetString("OLDP_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Add the record in grid .
        /// </summary>
        internal static string S3G_ErrMsg_AddGrid {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_AddGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select atleast one Location in the grid for Over Due Calculation.
        /// </summary>
        internal static string S3G_ErrMsg_Atleast_1ODI {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_Atleast_1ODI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to bind the grid.
        /// </summary>
        internal static string S3G_ErrMsg_BindGrid {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_BindGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Calulate ODI.
        /// </summary>
        internal static string S3G_ErrMsg_CalculateODI {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_CalculateODI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to calculate the Over Due Interest.
        /// </summary>
        internal static string S3G_ErrMsg_CalODI {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_CalODI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to canceling edit the record in grid.
        /// </summary>
        internal static string S3G_ErrMsg_CancelEditGrid {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_CancelEditGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Clear_FA the .
        /// </summary>
        internal static string S3G_ErrMsg_Clear {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Clear_FA the data.
        /// </summary>
        internal static string S3G_ErrMsg_ClearAll {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete the records.
        /// </summary>
        internal static string S3G_ErrMsg_Delete {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Delete the record in grid.
        /// </summary>
        internal static string S3G_ErrMsg_DeleteGrid {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_DeleteGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Edit the record in grid.
        /// </summary>
        internal static string S3G_ErrMsg_EditGrid {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_EditGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for selected combination is already exists.
        /// </summary>
        internal static string S3G_ErrMsg_ExistCombination {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_ExistCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the grid details..
        /// </summary>
        internal static string S3G_ErrMsg_GridEmpty {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_GridEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Insert/Update the .
        /// </summary>
        internal static string S3G_ErrMsg_InsertUpdate {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_InsertUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Load the Customer.
        /// </summary>
        internal static string S3G_ErrMsg_LoadCustomer {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_LoadCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Load the Over Due Interest.
        /// </summary>
        internal static string S3G_ErrMsg_LoadODI {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_LoadODI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Load the Prime Account No.
        /// </summary>
        internal static string S3G_ErrMsg_LoadPrimeACNum {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_LoadPrimeACNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Load the Sub Account Number.
        /// </summary>
        internal static string S3G_ErrMsg_LoadSubACNum {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_LoadSubACNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to closed the Account..
        /// </summary>
        internal static string S3G_ErrMsg_LoanAd_AcClosure {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_LoanAd_AcClosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PreMature Closure Done By given name does not match with the logged in name , unable to Pre Mature Closure of Account.
        /// </summary>
        internal static string S3G_ErrMsg_LoanAd_PreMatureClosure_Done {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_LoanAd_PreMatureClosure_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sent the mail..
        /// </summary>
        internal static string S3G_ErrMsg_MailSent {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_MailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current ODI Calculation Date should be greater than Last ODI Calculation Date.
        /// </summary>
        internal static string S3G_ErrMsg_ODICalDate_GT_LastODI {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_ODICalDate_GT_LastODI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current ODI Calculation Date should not be greater than Current Date.
        /// </summary>
        internal static string S3G_ErrMsg_ODICalDate_NGT_CD {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_ODICalDate_NGT_CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records not exists for Over Due Calculation.
        /// </summary>
        internal static string S3G_ErrMsg_ODICalNotExist {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_ODICalNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month is locked. Unable to Save Over Due Interest.
        /// </summary>
        internal static string S3G_ErrMsg_ODIMonthLockLOB {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_ODIMonthLockLOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Month is not locked. Unable to Save Over Due Interest.
        /// </summary>
        internal static string S3G_ErrMsg_ODIPrevMonthLockLOB {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_ODIPrevMonthLockLOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Revoke the data.
        /// </summary>
        internal static string S3G_ErrMsg_ODIRevoke {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_ODIRevoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Load the page .
        /// </summary>
        internal static string S3G_ErrMsg_PageLoad {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_PageLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to cancel the Preclosure Account..
        /// </summary>
        internal static string S3G_ErrMsg_PreClosure_Cancel {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_PreClosure_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to preview the document..
        /// </summary>
        internal static string S3G_ErrMsg_PreviewDoc {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_PreviewDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Revoke the Over Due Interest details.
        /// </summary>
        internal static string S3G_ErrMsg_RevokeODI {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_RevokeODI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the details.
        /// </summary>
        internal static string S3G_ErrMsg_Save {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Insert the Over Due Interest.
        /// </summary>
        internal static string S3G_ErrMsg_SaveODI {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_SaveODI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Date should be greater than or equal to Current Date.
        /// </summary>
        internal static string S3G_ErrMsg_ScheduleDate_GREQl {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_ScheduleDate_GREQl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schduled Time should be greater than 5 minutes for current date only.
        /// </summary>
        internal static string S3G_ErrMsg_ScheduleTime_GR_5M {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_ScheduleTime_GR_5M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the details.
        /// </summary>
        internal static string S3G_ErrMsg_Update {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update the record in grid.
        /// </summary>
        internal static string S3G_ErrMsg_UpdateGrid {
            get {
                return ResourceManager.GetString("S3G_ErrMsg_UpdateGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Entry Failed! Unable to Update Invoice Vendor Entry.
        /// </summary>
        internal static string S3G_INV_120 {
            get {
                return ResourceManager.GetString("S3G_INV_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Entry Failed! Unable to Create Invoice Vendor Entry.
        /// </summary>
        internal static string S3G_INV_121 {
            get {
                return ResourceManager.GetString("S3G_INV_121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Return Cancelled successfully.
        /// </summary>
        internal static string S3G_SucMsg_CLN_ChequeRetCancel {
            get {
                return ResourceManager.GetString("S3G_SucMsg_CLN_ChequeRetCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Return details added sucessfully for the Receipt Number .
        /// </summary>
        internal static string S3G_SucMsg_CLN_ChequeReturn {
            get {
                return ResourceManager.GetString("S3G_SucMsg_CLN_ChequeReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account closed succesfully.
        /// </summary>
        internal static string S3G_SucMsg_LoanAd_AcClosed {
            get {
                return ResourceManager.GetString("S3G_SucMsg_LoanAd_AcClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Prematurely closed  succesfully.
        /// </summary>
        internal static string S3G_SucMsg_LoanAd_PreMature_Closed {
            get {
                return ResourceManager.GetString("S3G_SucMsg_LoanAd_PreMature_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail sent successfully.
        /// </summary>
        internal static string S3G_SucMsg_MailSent {
            get {
                return ResourceManager.GetString("S3G_SucMsg_MailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Due Interest revoked successfully.
        /// </summary>
        internal static string S3G_SucMsg_RevokeODI {
            get {
                return ResourceManager.GetString("S3G_SucMsg_RevokeODI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Due Interest added successfully.
        /// </summary>
        internal static string S3G_SucMsg_SaveODI {
            get {
                return ResourceManager.GetString("S3G_SucMsg_SaveODI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Updated succesfully.
        /// </summary>
        internal static string S3G_SucMsg_Update {
            get {
                return ResourceManager.GetString("S3G_SucMsg_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Account Closure Done By.
        /// </summary>
        internal static string S3G_ValMsg_AcClosure_Done {
            get {
                return ResourceManager.GetString("S3G_ValMsg_AcClosure_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add atleast one record.
        /// </summary>
        internal static string S3G_ValMsg_AddAtleastOneRec {
            get {
                return ResourceManager.GetString("S3G_ValMsg_AddAtleastOneRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All approvals are already done for this record..
        /// </summary>
        internal static string S3G_ValMsg_Approval_3 {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Approval_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be updated.Records Approved already.
        /// </summary>
        internal static string S3G_ValMsg_ApprovedAlready {
            get {
                return ResourceManager.GetString("S3G_ValMsg_ApprovedAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Asset Code.
        /// </summary>
        internal static string S3G_ValMsg_AssetCode {
            get {
                return ResourceManager.GetString("S3G_ValMsg_AssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Asset Status.
        /// </summary>
        internal static string S3G_ValMsg_AssetStatus {
            get {
                return ResourceManager.GetString("S3G_ValMsg_AssetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base MLA is applicable to this Prime A/c Number - .
        /// </summary>
        internal static string S3G_ValMsg_BaseMLADefined {
            get {
                return ResourceManager.GetString("S3G_ValMsg_BaseMLADefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Location.
        /// </summary>
        internal static string S3G_ValMsg_Branch {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no receipt available for Challan generation.
        /// </summary>
        internal static string S3G_ValMsg_CGN {
            get {
                return ResourceManager.GetString("S3G_ValMsg_CGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Return needs to be Authorized or UnAuthorized and not previously Cancelled to be Cancelled.
        /// </summary>
        internal static string S3G_ValMsg_CLN_ChequeRetAuthorizedAndNotCancel {
            get {
                return ResourceManager.GetString("S3G_ValMsg_CLN_ChequeRetAuthorizedAndNotCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one Receipt exists for the Cheque Number, select a Receipt Number.
        /// </summary>
        internal static string S3G_ValMsg_CLN_MoreThen1Rec_Sel_ReceiptNo {
            get {
                return ResourceManager.GetString("S3G_ValMsg_CLN_MoreThen1Rec_Sel_ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Customer Code.
        /// </summary>
        internal static string S3G_ValMsg_CustomerCode {
            get {
                return ResourceManager.GetString("S3G_ValMsg_CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Date.
        /// </summary>
        internal static string S3g_ValMsg_Date {
            get {
                return ResourceManager.GetString("S3g_ValMsg_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date should be lesser than or equal to the End Date.
        /// </summary>
        internal static string S3G_ValMsg_DateCompare {
            get {
                return ResourceManager.GetString("S3G_ValMsg_DateCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Deposit Bank.
        /// </summary>
        internal static string S3g_ValMsg_DepositBank {
            get {
                return ResourceManager.GetString("S3g_ValMsg_DepositBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type is not defined in document number control or To Number is exceed.
        /// </summary>
        internal static string S3G_ValMsg_DocumentNoControl {
            get {
                return ResourceManager.GetString("S3G_ValMsg_DocumentNoControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Drawee Bank.
        /// </summary>
        internal static string S3g_ValMsg_DraweeBank {
            get {
                return ResourceManager.GetString("S3g_ValMsg_DraweeBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Effective From Date.
        /// </summary>
        internal static string S3G_ValMsg_EffectiveDate {
            get {
                return ResourceManager.GetString("S3G_ValMsg_EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details already exist.
        /// </summary>
        internal static string S3G_ValMsg_Exist {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Finance Amount.
        /// </summary>
        internal static string S3G_ValMsg_FinanceAmt {
            get {
                return ResourceManager.GetString("S3G_ValMsg_FinanceAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n\n Would you like to add one more Follow Up details?.
        /// </summary>
        internal static string S3G_ValMsg_FollowUp_Confirm {
            get {
                return ResourceManager.GetString("S3G_ValMsg_FollowUp_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Frequency.
        /// </summary>
        internal static string S3G_ValMsg_Frequency {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Inspection By.
        /// </summary>
        internal static string S3G_ValMsg_InspectionBy {
            get {
                return ResourceManager.GetString("S3G_ValMsg_InspectionBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Inspection Code.
        /// </summary>
        internal static string S3G_ValMsg_InspectionCode {
            get {
                return ResourceManager.GetString("S3G_ValMsg_InspectionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Inspection Date.
        /// </summary>
        internal static string S3G_ValMsg_InspectionDate {
            get {
                return ResourceManager.GetString("S3G_ValMsg_InspectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Inspection Time.
        /// </summary>
        internal static string S3G_ValMsg_InspectionTime {
            get {
                return ResourceManager.GetString("S3G_ValMsg_InspectionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Inspection Time in 12 HRS Format.
        /// </summary>
        internal static string S3G_ValMsg_Inspectiontimeformat {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Inspectiontimeformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Instrument Type.
        /// </summary>
        internal static string S3g_ValMsg_InstrumentType {
            get {
                return ResourceManager.GetString("S3g_ValMsg_InstrumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Closure Statement should be generated.
        /// </summary>
        internal static string S3G_ValMsg_LoanAd_AccClosure_Gen {
            get {
                return ResourceManager.GetString("S3G_ValMsg_LoanAd_AccClosure_Gen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \n\nWould you like to close one more account?.
        /// </summary>
        internal static string S3G_ValMsg_loanAd_AcClose1More {
            get {
                return ResourceManager.GetString("S3G_ValMsg_loanAd_AcClose1More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Closure Statement should be generated.
        /// </summary>
        internal static string S3G_ValMsg_LoanAd_AcClosure_Gene {
            get {
                return ResourceManager.GetString("S3G_ValMsg_LoanAd_AcClosure_Gene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name given does not match with the logged in name , unable to process Closure of Account.
        /// </summary>
        internal static string S3G_ValMsg_LoanAd_AcClosure_NameMatch {
            get {
                return ResourceManager.GetString("S3G_ValMsg_LoanAd_AcClosure_NameMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Preclosure Done By.
        /// </summary>
        internal static string S3G_ValMsg_LoanAd_AcPreClosure_Done {
            get {
                return ResourceManager.GetString("S3G_ValMsg_LoanAd_AcPreClosure_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Closure should be open for iniatiating Pre Mature closure.
        /// </summary>
        internal static string S3G_ValMsg_LoanAd_MthClosure_Iniate_PreMatureClosure {
            get {
                return ResourceManager.GetString("S3G_ValMsg_LoanAd_MthClosure_Iniate_PreMatureClosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Mature Closure Date should be equal or greater than current date.
        /// </summary>
        internal static string S3G_ValMsg_LoanAd_PreMatureDt_EqlOrGT_CurrentDt {
            get {
                return ResourceManager.GetString("S3G_ValMsg_LoanAd_PreMatureDt_EqlOrGT_CurrentDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Mature Closure Date should be lesser than Maturity Date.
        /// </summary>
        internal static string S3G_ValMsg_LoanAd_PreMatureDt_LT_MaturityDt {
            get {
                return ResourceManager.GetString("S3G_ValMsg_LoanAd_PreMatureDt_LT_MaturityDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Mature Closure Date should be with in the current month.
        /// </summary>
        internal static string S3G_ValMsg_LoanAd_PreMatureDt_WT_currentDt {
            get {
                return ResourceManager.GetString("S3G_ValMsg_LoanAd_PreMatureDt_WT_currentDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Line of Business.
        /// </summary>
        internal static string S3G_ValMsg_LOB {
            get {
                return ResourceManager.GetString("S3G_ValMsg_LOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Location.
        /// </summary>
        internal static string S3G_ValMsg_Location {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nWould you like to add one more.
        /// </summary>
        internal static string S3G_ValMsg_Next {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details does not exist.
        /// </summary>
        internal static string S3G_ValMsg_NotExist {
            get {
                return ResourceManager.GetString("S3G_ValMsg_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Current ODI Calculation Date.
        /// </summary>
        internal static string S3G_ValMsg_ODICalculationDate {
            get {
                return ResourceManager.GetString("S3G_ValMsg_ODICalculationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Schedule Date.
        /// </summary>
        internal static string S3G_ValMsg_ODIScheduleDate {
            get {
                return ResourceManager.GetString("S3G_ValMsg_ODIScheduleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Schedule Time.
        /// </summary>
        internal static string S3G_ValMsg_ODIScheduleTime {
            get {
                return ResourceManager.GetString("S3G_ValMsg_ODIScheduleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid Schedule Time.
        /// </summary>
        internal static string S3G_ValMsg_ODIValidTime {
            get {
                return ResourceManager.GetString("S3G_ValMsg_ODIValidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Product.
        /// </summary>
        internal static string S3G_ValMsg_Product {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Receipt Type.
        /// </summary>
        internal static string S3g_ValMsg_ReceipType {
            get {
                return ResourceManager.GetString("S3g_ValMsg_ReceipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details added successfully.
        /// </summary>
        internal static string S3G_ValMsg_Save {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Debt Collector Type..
        /// </summary>
        internal static string S3G_ValMsg_Select_DebtCollectorType {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Select_DebtCollectorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Employee Name..
        /// </summary>
        internal static string S3G_ValMsg_Select_EmpName {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Select_EmpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Prime Account Number.
        /// </summary>
        internal static string S3G_ValMsg_Select_PriAc {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Select_PriAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select either a Receipt No or enter a Cheque No.
        /// </summary>
        internal static string S3G_ValMsg_Select_ReceiptOrChequeNo {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Select_ReceiptOrChequeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Sub Account Number.
        /// </summary>
        internal static string S3G_ValMsg_Select_SubAc {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Select_SubAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status .
        /// </summary>
        internal static string S3G_ValMsg_Status {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details cannot be updated.Transaction exists.
        /// </summary>
        internal static string S3G_ValMsg_Tran {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Tran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details updated successfully.
        /// </summary>
        internal static string S3G_ValMsg_Update {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to upload.
        /// </summary>
        internal static string S3G_ValMsg_Upload {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Vendor.
        /// </summary>
        internal static string S3G_ValMsg_Vendor {
            get {
                return ResourceManager.GetString("S3G_ValMsg_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records found to load workflow.
        /// </summary>
        internal static string S3G_WF_NoRecords {
            get {
                return ResourceManager.GetString("S3G_WF_NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Sequence Number not defined.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the records for posting.
        /// </summary>
        internal static string _120 {
            get {
                return ResourceManager.GetString("120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the records. Repayment Structure Entry Failed.
        /// </summary>
        internal static string _140 {
            get {
                return ResourceManager.GetString("140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the records. Follow up Entry Failed.
        /// </summary>
        internal static string _141 {
            get {
                return ResourceManager.GetString("141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Sequence Number limit is exceeded.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Control Number cannot exceed 12 characters.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument not Banked - Cannot Process Return.
        /// </summary>
        internal static string _40 {
            get {
                return ResourceManager.GetString("40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument number does not exist..
        /// </summary>
        internal static string _41 {
            get {
                return ResourceManager.GetString("41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already cheque returned..
        /// </summary>
        internal static string _42 {
            get {
                return ResourceManager.GetString("42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred! Unable to save the records.
        /// </summary>
        internal static string _50 {
            get {
                return ResourceManager.GetString("50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Sequence Number not defined for posting.
        /// </summary>
        internal static string _51 {
            get {
                return ResourceManager.GetString("51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Document Sequence Number limit is exceeded for posting.
        /// </summary>
        internal static string _52 {
            get {
                return ResourceManager.GetString("52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash flow master not defined for posting.
        /// </summary>
        internal static string _53 {
            get {
                return ResourceManager.GetString("53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank GL Code not defined in Account Setup Master .
        /// </summary>
        internal static string _54 {
            get {
                return ResourceManager.GetString("54", resourceCulture);
            }
        }
    }
}
