<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:tns="http://tempuri.org/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ApprovalMgtServices" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SymmetricBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:ProtectionToken>
              <wsp:Policy>
                <sp:SecureConversationToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                  <wsp:Policy>
                    <sp:RequireDerivedKeys />
                    <sp:BootstrapPolicy>
                      <wsp:Policy>
                        <sp:SignedParts>
                          <sp:Body />
                          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
                        </sp:SignedParts>
                        <sp:EncryptedParts>
                          <sp:Body />
                        </sp:EncryptedParts>
                        <sp:SymmetricBinding>
                          <wsp:Policy>
                            <sp:ProtectionToken>
                              <wsp:Policy>
                                <sp:SpnegoContextToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                                  <wsp:Policy>
                                    <sp:RequireDerivedKeys />
                                  </wsp:Policy>
                                </sp:SpnegoContextToken>
                              </wsp:Policy>
                            </sp:ProtectionToken>
                            <sp:AlgorithmSuite>
                              <wsp:Policy>
                                <sp:Basic256 />
                              </wsp:Policy>
                            </sp:AlgorithmSuite>
                            <sp:Layout>
                              <wsp:Policy>
                                <sp:Strict />
                              </wsp:Policy>
                            </sp:Layout>
                            <sp:IncludeTimestamp />
                            <sp:EncryptSignature />
                            <sp:OnlySignEntireHeadersAndBody />
                          </wsp:Policy>
                        </sp:SymmetricBinding>
                        <sp:Wss11>
                          <wsp:Policy />
                        </sp:Wss11>
                        <sp:Trust10>
                          <wsp:Policy>
                            <sp:MustSupportIssuedTokens />
                            <sp:RequireClientEntropy />
                            <sp:RequireServerEntropy />
                          </wsp:Policy>
                        </sp:Trust10>
                      </wsp:Policy>
                    </sp:BootstrapPolicy>
                  </wsp:Policy>
                </sp:SecureConversationToken>
              </wsp:Policy>
            </sp:ProtectionToken>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic256 />
              </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
              <wsp:Policy>
                <sp:Strict />
              </wsp:Policy>
            </sp:Layout>
            <sp:IncludeTimestamp />
            <sp:EncryptSignature />
            <sp:OnlySignEntireHeadersAndBody />
          </wsp:Policy>
        </sp:SymmetricBinding>
        <sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy />
        </sp:Wss11>
        <sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:MustSupportIssuedTokens />
            <sp:RequireClientEntropy />
            <sp:RequireServerEntropy />
          </wsp:Policy>
        </sp:Trust10>
        <wsaw:UsingAddressing />
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubCreateApprovals_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubCreateApprovals_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubCreateApprovals_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubCreateSubLimitApprovals_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubCreateSubLimitApprovals_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubCreateSubLimitApprovals_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubRevokeOrUpdateApprovedDetails_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubRevokeOrUpdateApprovedDetails_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubRevokeOrUpdateApprovedDetails_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubCommonCreateApprovals_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubCommonCreateApprovals_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubCommonCreateApprovals_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubCommonRevokeApprovals_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubCommonRevokeApprovals_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubCommonRevokeApprovals_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubCreateScheduleJobForReport_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubCreateScheduleJobForReport_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IApprovalMgtServices_FunPubCreateScheduleJobForReport_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsdl:types>
    <xsd:schema targetNamespace="http://tempuri.org/Imports">
      <xsd:import schemaLocation="http://localhost:3220/LoanAdmin/ApprovalMgtServices.svc?xsd=xsd0" namespace="http://tempuri.org/" />
      <xsd:import schemaLocation="http://localhost:3220/LoanAdmin/ApprovalMgtServices.svc?xsd=xsd3" namespace="http://schemas.datacontract.org/2004/07/S3GServiceLayer" />
      <xsd:import schemaLocation="http://localhost:3220/LoanAdmin/ApprovalMgtServices.svc?xsd=xsd1" namespace="http://schemas.microsoft.com/2003/10/Serialization/" />
      <xsd:import schemaLocation="http://localhost:3220/LoanAdmin/ApprovalMgtServices.svc?xsd=xsd2" namespace="http://schemas.datacontract.org/2004/07/S3GBusEntity" />
      <xsd:import schemaLocation="http://localhost:3220/LoanAdmin/ApprovalMgtServices.svc?xsd=xsd4" namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="IApprovalMgtServices_FunPubCreateApprovals_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateApprovals" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubCreateApprovals_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateApprovalsResponse" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubCreateApprovals_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q1="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q1:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubCreateSubLimitApprovals_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateSubLimitApprovals" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubCreateSubLimitApprovals_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateSubLimitApprovalsResponse" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubCreateSubLimitApprovals_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q2="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q2:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubRevokeOrUpdateApprovedDetails_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubRevokeOrUpdateApprovedDetails" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubRevokeOrUpdateApprovedDetails_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubRevokeOrUpdateApprovedDetailsResponse" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubRevokeOrUpdateApprovedDetails_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q3="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q3:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubCommonCreateApprovals_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCommonCreateApprovals" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubCommonCreateApprovals_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCommonCreateApprovalsResponse" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubCommonCreateApprovals_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q4="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q4:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubCommonRevokeApprovals_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCommonRevokeApprovals" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubCommonRevokeApprovals_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCommonRevokeApprovalsResponse" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubCommonRevokeApprovals_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q5="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q5:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubCreateScheduleJobForReport_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateScheduleJobForReport" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubCreateScheduleJobForReport_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateScheduleJobForReportResponse" />
  </wsdl:message>
  <wsdl:message name="IApprovalMgtServices_FunPubCreateScheduleJobForReport_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q6="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q6:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:portType name="IApprovalMgtServices">
    <wsdl:operation name="FunPubCreateApprovals">
      <wsdl:input wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubCreateApprovals" message="tns:IApprovalMgtServices_FunPubCreateApprovals_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubCreateApprovalsResponse" message="tns:IApprovalMgtServices_FunPubCreateApprovals_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubCreateApprovalsClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IApprovalMgtServices_FunPubCreateApprovals_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateSubLimitApprovals">
      <wsdl:input wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubCreateSubLimitApprovals" message="tns:IApprovalMgtServices_FunPubCreateSubLimitApprovals_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubCreateSubLimitApprovalsResponse" message="tns:IApprovalMgtServices_FunPubCreateSubLimitApprovals_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubCreateSubLimitApprovalsClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IApprovalMgtServices_FunPubCreateSubLimitApprovals_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubRevokeOrUpdateApprovedDetails">
      <wsdl:input wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubRevokeOrUpdateApprovedDetails" message="tns:IApprovalMgtServices_FunPubRevokeOrUpdateApprovedDetails_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubRevokeOrUpdateApprovedDetailsResponse" message="tns:IApprovalMgtServices_FunPubRevokeOrUpdateApprovedDetails_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubRevokeOrUpdateApprovedDetailsClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IApprovalMgtServices_FunPubRevokeOrUpdateApprovedDetails_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubCommonCreateApprovals">
      <wsdl:input wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubCommonCreateApprovals" message="tns:IApprovalMgtServices_FunPubCommonCreateApprovals_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubCommonCreateApprovalsResponse" message="tns:IApprovalMgtServices_FunPubCommonCreateApprovals_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubCommonCreateApprovalsClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IApprovalMgtServices_FunPubCommonCreateApprovals_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubCommonRevokeApprovals">
      <wsdl:input wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubCommonRevokeApprovals" message="tns:IApprovalMgtServices_FunPubCommonRevokeApprovals_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubCommonRevokeApprovalsResponse" message="tns:IApprovalMgtServices_FunPubCommonRevokeApprovals_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubCommonRevokeApprovalsClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IApprovalMgtServices_FunPubCommonRevokeApprovals_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateScheduleJobForReport">
      <wsdl:input wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubCreateScheduleJobForReport" message="tns:IApprovalMgtServices_FunPubCreateScheduleJobForReport_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubCreateScheduleJobForReportResponse" message="tns:IApprovalMgtServices_FunPubCreateScheduleJobForReport_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IApprovalMgtServices/FunPubCreateScheduleJobForReportClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IApprovalMgtServices_FunPubCreateScheduleJobForReport_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="WSHttpBinding_IApprovalMgtServices" type="tns:IApprovalMgtServices">
    <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_policy" />
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="FunPubCreateApprovals">
      <soap12:operation soapAction="http://tempuri.org/IApprovalMgtServices/FunPubCreateApprovals" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubCreateApprovals_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubCreateApprovals_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubCreateApprovals_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateSubLimitApprovals">
      <soap12:operation soapAction="http://tempuri.org/IApprovalMgtServices/FunPubCreateSubLimitApprovals" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubCreateSubLimitApprovals_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubCreateSubLimitApprovals_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubCreateSubLimitApprovals_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubRevokeOrUpdateApprovedDetails">
      <soap12:operation soapAction="http://tempuri.org/IApprovalMgtServices/FunPubRevokeOrUpdateApprovedDetails" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubRevokeOrUpdateApprovedDetails_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubRevokeOrUpdateApprovedDetails_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubRevokeOrUpdateApprovedDetails_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubCommonCreateApprovals">
      <soap12:operation soapAction="http://tempuri.org/IApprovalMgtServices/FunPubCommonCreateApprovals" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubCommonCreateApprovals_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubCommonCreateApprovals_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubCommonCreateApprovals_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubCommonRevokeApprovals">
      <soap12:operation soapAction="http://tempuri.org/IApprovalMgtServices/FunPubCommonRevokeApprovals" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubCommonRevokeApprovals_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubCommonRevokeApprovals_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubCommonRevokeApprovals_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateScheduleJobForReport">
      <soap12:operation soapAction="http://tempuri.org/IApprovalMgtServices/FunPubCreateScheduleJobForReport" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubCreateScheduleJobForReport_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubCreateScheduleJobForReport_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IApprovalMgtServices_FunPubCreateScheduleJobForReport_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ApprovalMgtServices">
    <wsdl:port name="WSHttpBinding_IApprovalMgtServices" binding="tns:WSHttpBinding_IApprovalMgtServices">
      <soap12:address location="http://localhost:3220/LoanAdmin/ApprovalMgtServices.svc" />
      <wsa10:EndpointReference>
        <wsa10:Address>http://localhost:3220/LoanAdmin/ApprovalMgtServices.svc</wsa10:Address>
        <Identity xmlns="http://schemas.xmlsoap.org/ws/2006/02/addressingidentity">
          <Dns>localhost</Dns>
        </Identity>
      </wsa10:EndpointReference>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>