<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:tns="http://tempuri.org/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" name="RuleCardMgtServices" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SymmetricBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:ProtectionToken>
              <wsp:Policy>
                <sp:SecureConversationToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                  <wsp:Policy>
                    <sp:RequireDerivedKeys />
                    <sp:BootstrapPolicy>
                      <wsp:Policy>
                        <sp:SignedParts>
                          <sp:Body />
                          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
                          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
                        </sp:SignedParts>
                        <sp:EncryptedParts>
                          <sp:Body />
                        </sp:EncryptedParts>
                        <sp:SymmetricBinding>
                          <wsp:Policy>
                            <sp:ProtectionToken>
                              <wsp:Policy>
                                <sp:SpnegoContextToken sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
                                  <wsp:Policy>
                                    <sp:RequireDerivedKeys />
                                  </wsp:Policy>
                                </sp:SpnegoContextToken>
                              </wsp:Policy>
                            </sp:ProtectionToken>
                            <sp:AlgorithmSuite>
                              <wsp:Policy>
                                <sp:Basic256 />
                              </wsp:Policy>
                            </sp:AlgorithmSuite>
                            <sp:Layout>
                              <wsp:Policy>
                                <sp:Strict />
                              </wsp:Policy>
                            </sp:Layout>
                            <sp:IncludeTimestamp />
                            <sp:EncryptSignature />
                            <sp:OnlySignEntireHeadersAndBody />
                          </wsp:Policy>
                        </sp:SymmetricBinding>
                        <sp:Wss11>
                          <wsp:Policy>
                            <sp:MustSupportRefKeyIdentifier />
                            <sp:MustSupportRefIssuerSerial />
                            <sp:MustSupportRefThumbprint />
                            <sp:MustSupportRefEncryptedKey />
                          </wsp:Policy>
                        </sp:Wss11>
                        <sp:Trust10>
                          <wsp:Policy>
                            <sp:MustSupportIssuedTokens />
                            <sp:RequireClientEntropy />
                            <sp:RequireServerEntropy />
                          </wsp:Policy>
                        </sp:Trust10>
                      </wsp:Policy>
                    </sp:BootstrapPolicy>
                  </wsp:Policy>
                </sp:SecureConversationToken>
              </wsp:Policy>
            </sp:ProtectionToken>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic256 />
              </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
              <wsp:Policy>
                <sp:Strict />
              </wsp:Policy>
            </sp:Layout>
            <sp:IncludeTimestamp />
            <sp:EncryptSignature />
            <sp:OnlySignEntireHeadersAndBody />
          </wsp:Policy>
        </sp:SymmetricBinding>
        <sp:Wss11 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:MustSupportRefKeyIdentifier />
            <sp:MustSupportRefIssuerSerial />
            <sp:MustSupportRefThumbprint />
            <sp:MustSupportRefEncryptedKey />
          </wsp:Policy>
        </sp:Wss11>
        <sp:Trust10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:MustSupportIssuedTokens />
            <sp:RequireClientEntropy />
            <sp:RequireServerEntropy />
          </wsp:Policy>
        </sp:Trust10>
        <wsaw:UsingAddressing />
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubCreateAuthorizationRuleCard_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubCreateAuthorizationRuleCard_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubCreateAuthorizationRuleCard_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubModifyAuthorizationRuleCard_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubModifyAuthorizationRuleCard_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubModifyAuthorizationRuleCard_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubQueryTransactionTypeMaster_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubQueryTransactionTypeMaster_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubQueryTransactionTypeMaster_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubQueryConstitutionMaster_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubQueryConstitutionMaster_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubQueryConstitutionMaster_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubQueryAuthorizationRuleCard_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubQueryAuthorizationRuleCard_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubQueryAuthorizationRuleCard_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubCreateROIRulesInt_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubCreateROIRulesInt_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubCreateROIRulesInt_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubModifyROIRulesInt_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubModifyROIRulesInt_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubModifyROIRulesInt_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubQueryROIRules_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubQueryROIRules_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubQueryROIRules_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubCreatePaymentRuleCardInt_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubCreatePaymentRuleCardInt_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubCreatePaymentRuleCardInt_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubModifyPaymentRuleCardInt_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubModifyPaymentRuleCardInt_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubModifyPaymentRuleCardInt_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubQueryPaymentRuleCard_Input_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubQueryPaymentRuleCard_output_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsp:Policy wsu:Id="WSHttpBinding_IRuleCardMgtServices_FunPubQueryPaymentRuleCard_ClsPubFaultExceptionFault_Fault">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:SignedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
          <sp:Header Name="To" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="From" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="FaultTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="ReplyTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="MessageID" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="RelatesTo" Namespace="http://www.w3.org/2005/08/addressing" />
          <sp:Header Name="Action" Namespace="http://www.w3.org/2005/08/addressing" />
        </sp:SignedParts>
        <sp:EncryptedParts xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <sp:Body />
        </sp:EncryptedParts>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsdl:types>
    <xsd:schema targetNamespace="http://tempuri.org/Imports">
      <xsd:import schemaLocation="http://localhost:3220/Origination/RuleCardMgtServices.svc?xsd=xsd0" namespace="http://tempuri.org/" />
      <xsd:import schemaLocation="http://localhost:3220/Origination/RuleCardMgtServices.svc?xsd=xsd3" namespace="http://schemas.datacontract.org/2004/07/S3GServiceLayer" />
      <xsd:import schemaLocation="http://localhost:3220/Origination/RuleCardMgtServices.svc?xsd=xsd1" namespace="http://schemas.microsoft.com/2003/10/Serialization/" />
      <xsd:import schemaLocation="http://localhost:3220/Origination/RuleCardMgtServices.svc?xsd=xsd2" namespace="http://schemas.datacontract.org/2004/07/S3GBusEntity" />
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="IRuleCardMgtServices_FunPubCreateAuthorizationRuleCard_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateAuthorizationRuleCard" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubCreateAuthorizationRuleCard_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateAuthorizationRuleCardResponse" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubCreateAuthorizationRuleCard_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q1="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q1:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubModifyAuthorizationRuleCard_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubModifyAuthorizationRuleCard" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubModifyAuthorizationRuleCard_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubModifyAuthorizationRuleCardResponse" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubModifyAuthorizationRuleCard_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q2="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q2:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubQueryTransactionTypeMaster_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubQueryTransactionTypeMaster" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubQueryTransactionTypeMaster_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubQueryTransactionTypeMasterResponse" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubQueryTransactionTypeMaster_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q3="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q3:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubQueryConstitutionMaster_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubQueryConstitutionMaster" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubQueryConstitutionMaster_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubQueryConstitutionMasterResponse" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubQueryConstitutionMaster_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q4="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q4:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubQueryAuthorizationRuleCard_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubQueryAuthorizationRuleCard" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubQueryAuthorizationRuleCard_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubQueryAuthorizationRuleCardResponse" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubQueryAuthorizationRuleCard_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q5="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q5:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubCreateROIRulesInt_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateROIRulesInt" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubCreateROIRulesInt_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreateROIRulesIntResponse" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubCreateROIRulesInt_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q6="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q6:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubModifyROIRulesInt_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubModifyROIRulesInt" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubModifyROIRulesInt_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubModifyROIRulesIntResponse" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubModifyROIRulesInt_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q7="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q7:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubQueryROIRules_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubQueryROIRules" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubQueryROIRules_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubQueryROIRulesResponse" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubQueryROIRules_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q8="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q8:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubCreatePaymentRuleCardInt_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreatePaymentRuleCardInt" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubCreatePaymentRuleCardInt_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubCreatePaymentRuleCardIntResponse" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubCreatePaymentRuleCardInt_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q9="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q9:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubModifyPaymentRuleCardInt_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubModifyPaymentRuleCardInt" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubModifyPaymentRuleCardInt_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubModifyPaymentRuleCardIntResponse" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubModifyPaymentRuleCardInt_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q10="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q10:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubQueryPaymentRuleCard_InputMessage">
    <wsdl:part name="parameters" element="tns:FunPubQueryPaymentRuleCard" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubQueryPaymentRuleCard_OutputMessage">
    <wsdl:part name="parameters" element="tns:FunPubQueryPaymentRuleCardResponse" />
  </wsdl:message>
  <wsdl:message name="IRuleCardMgtServices_FunPubQueryPaymentRuleCard_ClsPubFaultExceptionFault_FaultMessage">
    <wsdl:part xmlns:q11="http://schemas.datacontract.org/2004/07/S3GServiceLayer" name="detail" element="q11:ClsPubFaultException" />
  </wsdl:message>
  <wsdl:portType name="IRuleCardMgtServices">
    <wsdl:operation name="FunPubCreateAuthorizationRuleCard">
      <wsdl:input wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubCreateAuthorizationRuleCard" message="tns:IRuleCardMgtServices_FunPubCreateAuthorizationRuleCard_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubCreateAuthorizationRuleCardResponse" message="tns:IRuleCardMgtServices_FunPubCreateAuthorizationRuleCard_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubCreateAuthorizationRuleCardClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IRuleCardMgtServices_FunPubCreateAuthorizationRuleCard_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubModifyAuthorizationRuleCard">
      <wsdl:input wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubModifyAuthorizationRuleCard" message="tns:IRuleCardMgtServices_FunPubModifyAuthorizationRuleCard_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubModifyAuthorizationRuleCardResponse" message="tns:IRuleCardMgtServices_FunPubModifyAuthorizationRuleCard_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubModifyAuthorizationRuleCardClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IRuleCardMgtServices_FunPubModifyAuthorizationRuleCard_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubQueryTransactionTypeMaster">
      <wsdl:input wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubQueryTransactionTypeMaster" message="tns:IRuleCardMgtServices_FunPubQueryTransactionTypeMaster_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubQueryTransactionTypeMasterResponse" message="tns:IRuleCardMgtServices_FunPubQueryTransactionTypeMaster_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubQueryTransactionTypeMasterClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IRuleCardMgtServices_FunPubQueryTransactionTypeMaster_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubQueryConstitutionMaster">
      <wsdl:input wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubQueryConstitutionMaster" message="tns:IRuleCardMgtServices_FunPubQueryConstitutionMaster_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubQueryConstitutionMasterResponse" message="tns:IRuleCardMgtServices_FunPubQueryConstitutionMaster_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubQueryConstitutionMasterClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IRuleCardMgtServices_FunPubQueryConstitutionMaster_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubQueryAuthorizationRuleCard">
      <wsdl:input wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubQueryAuthorizationRuleCard" message="tns:IRuleCardMgtServices_FunPubQueryAuthorizationRuleCard_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubQueryAuthorizationRuleCardResponse" message="tns:IRuleCardMgtServices_FunPubQueryAuthorizationRuleCard_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubQueryAuthorizationRuleCardClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IRuleCardMgtServices_FunPubQueryAuthorizationRuleCard_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateROIRulesInt">
      <wsdl:input wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubCreateROIRulesInt" message="tns:IRuleCardMgtServices_FunPubCreateROIRulesInt_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubCreateROIRulesIntResponse" message="tns:IRuleCardMgtServices_FunPubCreateROIRulesInt_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubCreateROIRulesIntClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IRuleCardMgtServices_FunPubCreateROIRulesInt_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubModifyROIRulesInt">
      <wsdl:input wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubModifyROIRulesInt" message="tns:IRuleCardMgtServices_FunPubModifyROIRulesInt_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubModifyROIRulesIntResponse" message="tns:IRuleCardMgtServices_FunPubModifyROIRulesInt_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubModifyROIRulesIntClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IRuleCardMgtServices_FunPubModifyROIRulesInt_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubQueryROIRules">
      <wsdl:input wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubQueryROIRules" message="tns:IRuleCardMgtServices_FunPubQueryROIRules_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubQueryROIRulesResponse" message="tns:IRuleCardMgtServices_FunPubQueryROIRules_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubQueryROIRulesClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IRuleCardMgtServices_FunPubQueryROIRules_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubCreatePaymentRuleCardInt">
      <wsdl:input wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubCreatePaymentRuleCardInt" message="tns:IRuleCardMgtServices_FunPubCreatePaymentRuleCardInt_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubCreatePaymentRuleCardIntResponse" message="tns:IRuleCardMgtServices_FunPubCreatePaymentRuleCardInt_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubCreatePaymentRuleCardIntClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IRuleCardMgtServices_FunPubCreatePaymentRuleCardInt_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubModifyPaymentRuleCardInt">
      <wsdl:input wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubModifyPaymentRuleCardInt" message="tns:IRuleCardMgtServices_FunPubModifyPaymentRuleCardInt_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubModifyPaymentRuleCardIntResponse" message="tns:IRuleCardMgtServices_FunPubModifyPaymentRuleCardInt_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubModifyPaymentRuleCardIntClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IRuleCardMgtServices_FunPubModifyPaymentRuleCardInt_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
    <wsdl:operation name="FunPubQueryPaymentRuleCard">
      <wsdl:input wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubQueryPaymentRuleCard" message="tns:IRuleCardMgtServices_FunPubQueryPaymentRuleCard_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubQueryPaymentRuleCardResponse" message="tns:IRuleCardMgtServices_FunPubQueryPaymentRuleCard_OutputMessage" />
      <wsdl:fault wsaw:Action="http://tempuri.org/IRuleCardMgtServices/FunPubQueryPaymentRuleCardClsPubFaultExceptionFault" name="ClsPubFaultExceptionFault" message="tns:IRuleCardMgtServices_FunPubQueryPaymentRuleCard_ClsPubFaultExceptionFault_FaultMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="WSHttpBinding_IRuleCardMgtServices" type="tns:IRuleCardMgtServices">
    <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_policy" />
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="FunPubCreateAuthorizationRuleCard">
      <soap12:operation soapAction="http://tempuri.org/IRuleCardMgtServices/FunPubCreateAuthorizationRuleCard" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubCreateAuthorizationRuleCard_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubCreateAuthorizationRuleCard_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubCreateAuthorizationRuleCard_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubModifyAuthorizationRuleCard">
      <soap12:operation soapAction="http://tempuri.org/IRuleCardMgtServices/FunPubModifyAuthorizationRuleCard" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubModifyAuthorizationRuleCard_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubModifyAuthorizationRuleCard_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubModifyAuthorizationRuleCard_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubQueryTransactionTypeMaster">
      <soap12:operation soapAction="http://tempuri.org/IRuleCardMgtServices/FunPubQueryTransactionTypeMaster" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubQueryTransactionTypeMaster_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubQueryTransactionTypeMaster_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubQueryTransactionTypeMaster_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubQueryConstitutionMaster">
      <soap12:operation soapAction="http://tempuri.org/IRuleCardMgtServices/FunPubQueryConstitutionMaster" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubQueryConstitutionMaster_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubQueryConstitutionMaster_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubQueryConstitutionMaster_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubQueryAuthorizationRuleCard">
      <soap12:operation soapAction="http://tempuri.org/IRuleCardMgtServices/FunPubQueryAuthorizationRuleCard" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubQueryAuthorizationRuleCard_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubQueryAuthorizationRuleCard_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubQueryAuthorizationRuleCard_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubCreateROIRulesInt">
      <soap12:operation soapAction="http://tempuri.org/IRuleCardMgtServices/FunPubCreateROIRulesInt" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubCreateROIRulesInt_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubCreateROIRulesInt_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubCreateROIRulesInt_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubModifyROIRulesInt">
      <soap12:operation soapAction="http://tempuri.org/IRuleCardMgtServices/FunPubModifyROIRulesInt" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubModifyROIRulesInt_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubModifyROIRulesInt_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubModifyROIRulesInt_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubQueryROIRules">
      <soap12:operation soapAction="http://tempuri.org/IRuleCardMgtServices/FunPubQueryROIRules" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubQueryROIRules_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubQueryROIRules_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubQueryROIRules_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubCreatePaymentRuleCardInt">
      <soap12:operation soapAction="http://tempuri.org/IRuleCardMgtServices/FunPubCreatePaymentRuleCardInt" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubCreatePaymentRuleCardInt_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubCreatePaymentRuleCardInt_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubCreatePaymentRuleCardInt_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubModifyPaymentRuleCardInt">
      <soap12:operation soapAction="http://tempuri.org/IRuleCardMgtServices/FunPubModifyPaymentRuleCardInt" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubModifyPaymentRuleCardInt_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubModifyPaymentRuleCardInt_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubModifyPaymentRuleCardInt_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="FunPubQueryPaymentRuleCard">
      <soap12:operation soapAction="http://tempuri.org/IRuleCardMgtServices/FunPubQueryPaymentRuleCard" style="document" />
      <wsdl:input>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubQueryPaymentRuleCard_Input_policy" />
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubQueryPaymentRuleCard_output_policy" />
        <soap12:body use="literal" />
      </wsdl:output>
      <wsdl:fault name="ClsPubFaultExceptionFault">
        <wsp:PolicyReference URI="#WSHttpBinding_IRuleCardMgtServices_FunPubQueryPaymentRuleCard_ClsPubFaultExceptionFault_Fault" />
        <soap12:fault use="literal" name="ClsPubFaultExceptionFault" namespace="" />
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RuleCardMgtServices">
    <wsdl:port name="WSHttpBinding_IRuleCardMgtServices" binding="tns:WSHttpBinding_IRuleCardMgtServices">
      <soap12:address location="http://localhost:3220/Origination/RuleCardMgtServices.svc" />
      <wsa10:EndpointReference>
        <wsa10:Address>http://localhost:3220/Origination/RuleCardMgtServices.svc</wsa10:Address>
        <Identity xmlns="http://schemas.xmlsoap.org/ws/2006/02/addressingidentity">
          <Dns>localhost</Dns>
        </Identity>
      </wsa10:EndpointReference>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>